[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#1f4d6f'

[colors.cursor]
text = '#1e1e2e'
cursor = '#74c7ec'

[colors.normal]
black   = '#181825'
red     = '#ff709e'
green   = '#74ec81'
yellow  = '#fff670'
blue    = '#57b6e0'
magenta = '#074d6d'
cyan    = '#74c7ec'
white   = '#e8f3f7'

[colors.bright]
black   = '#8d9599'
red     = '#ff9dbd'
green   = '#a4ffae'
yellow  = '#fff9a4'
blue    = '#90ddff'
magenta = '#a4e3ff'
cyan    = '#c4edff'
white   = '#f8fcff'
