#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	Author	-	gh0stzk
#	Repo	-	https://github.com/gh0stzk/dotfiles
#	Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

MonitorSetup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules
bspc desktop -focus 1
bspc config window_gap 2
bspc config split_ratio 0.53
bspc config single_monocle true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

# Set system vars for polybar
"$HOME"/.config/bspwm/src/SetSysVars
# Launch sxhkd daemon
run sxhkd -c "${HOME}"/.config/bspwm/src/config/sxhkdrc

# start dunst
run /usr/bin/dunst

# Load current theme
"${HOME}"/.config/bspwm/src/Theme.sh

# Launch picom
run picom --config "${HOME}"/.config/bspwm/src/config/picom.conf

# Launch xsettingsd
run xsettingsd --config="${HOME}"/.config/bspwm/src/config/xsettingsd

# Launch eww daemon
run eww -c "${HOME}"/.config/bspwm/eww daemon

# Launch clipboard daemon
run clipcatd

# Launch polkit
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# End one time code
#######################################
########## START CUSTOM APPS ##########
#######################################
# Launch power manager
run xfce4-power-manager --sm-client-disable

# start keepassxc
# run keepassxc
run bitwarden-desktop

# start nextcloud
run "/usr/bin/nextcloud" --background

# Start Conky
run ~/.config/conky/conkyx-start.sh
bspc rule -a conky state=floating manage=off

# Start udiskie
# Kill if already running
run udiskie -t --no-notify

# Start Telegram
run telegram-desktop -startintray

# Kde Connect
run kdeconnect-indicator

# Start zdg-desktop-portal
#run xdg-desktop-portal-gtk
#run xdg-desktop-portal

# start Plank
run sleep 10 && plank
bspc rule -a Plank layer=above manage=on border=off

# start Megasync
run sleep 10 && megasync
bspc rule -a Megasync layer=above manage=on border=off