#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## launch kitty with bspwm config

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/kitty/kitty.conf"

if [ "$1" == "--float" ]; then
	kitty --class 'alacritty-float,alacritty-float' --config "$CONFIG"
elif [ "$1" == "--full" ]; then
	kitty --class 'Fullscreen,Fullscreen' --config "$CONFIG" \
			  -o window.startup_mode=fullscreen \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=14
else
	kitty --config "$CONFIG"
fi
