#!/usr/bin/env bash
#  ███████╗██╗  ██╗████████╗███████╗██████╗ ███╗   ██╗ █████╗ ██╗
#  ██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██║
#  █████╗   ╚███╔╝    ██║   █████╗  ██████╔╝██╔██╗ ██║███████║██║
#  ██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗██║╚██╗██║██╔══██║██║
#  ███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║██║ ╚████║██║  ██║███████╗
#  ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝
#
#              ██████╗ ██╗   ██╗██╗     ███████╗███████╗
#              ██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
#              ██████╔╝██║   ██║██║     █████╗  ███████╗
#              ██╔══██╗██║   ██║██║     ██╔══╝  ╚════██║
#              ██║  ██║╚██████╔╝███████╗███████╗███████║
#              ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝
#	[Author] : gh0stzk
#	 [Url]   : https://github.com/gh0stzk/dotfiles
#

wid=$1
class=$2
instance=$3
consequences=$4

# Function to calculate dimensions based on percentages
calculate_dimensions() {
  local width_percent=$1
  local height_percent=$2

  # Get screen dimensions
  read -r screen_width screen_height < <(xdpyinfo | awk '/dimensions:/ {print $2}' | tr 'x' ' ')

  # Calculate dimensions in pixels
  local width=$(((screen_width * width_percent + 50) / 100))
  local height=$(((screen_height * height_percent + 50) / 100))

  printf '%dx%d+0+0\n' "$width" "$height"
}

result() {
  eval "$consequences"
  [ "$state" ] || echo "$1"
}

case "$class" in
FloaTerm)
  dimensions=$(calculate_dimensions 81 82)
  result "state=floating center=on rectangle=$dimensions"
  ;;
Updating)
  dimensions=$(calculate_dimensions 65 55)
  result "state=floating sticky=on center=on rectangle=$dimensions"
  ;;
RangerTerm)
  dimensions=$(calculate_dimensions 51 34)
  result "state=floating center=on rectangle=$dimensions"
  ;;
MusicTerm)
  dimensions=$(calculate_dimensions 78 71)
  result "state=floating center=on rectangle=$dimensions"
  ;;
FetchTerm)
  dimensions=$(calculate_dimensions 31 58)
  result "state=floating center=on rectangle=$dimensions"
  ;;
RiceEditor)
  result "state=floating focus=on center=on"
  ;;
mpv)
  dimensions=$(calculate_dimensions 73 73)
  result "state=floating focus=on center=on rectangle=$dimensions"
  ;;
Viewnior | Bitwarden | keepassxc | Keepassxc | ristretto | Ristretto | wireguird | Wireguird)
  result "state=floating focus=on center=on"
  ;;
TelegramDesktop | thunderbird)
  result "desktop=^5 follow=on"
  ;;
retroarch)
  result "state=pseudo_tiled desktop=^6"
  ;;
pavucontrol)
  result "state=floating center=on"
  ;;
Virt-manager)
  result "state=floating desktop=^5 follow=on center=on"
  ;;
Thunar)
  result "desktop=^2 follow=on"
  ;;
Geany)
  result "desktop=^4 follow=on"
  ;;
Mousepad)
  result "desktop=^4 follow=on"
  ;;
kitty)
  result "desktop=^1 follow=on"
  ;;
firefox | Navigator | Google-chrome)
  result "desktop=^3 follow=on"
  ;;
Transmission-gtk | Evince)
  result "desktop=^6 follow=on"
  ;;
Spotify | Deezer)
  result "state=floating desktop=^6 follow=on center=on"
  ;;
Inkscape | Gimp*)
  result "desktop=^6 follow=on"
  ;;
esac

case "$instance" in
Toolkit)
  result "state=floating sticky=on rectangle=500x290+1054+593"
  ;;
esac
