#!/usr/bin/env bash

options=(
  " Bloquear"
  " Suspender"
  " Salir"
  " Reiniciar"
  " Apagar"
)

rofi_cmd() {
  rofi -dmenu \
    -p "Goodbye ${USER}" \
    -mesg "Uptime: $(uptime -p | sed -e 's/up //g')" \
    -theme "$HOME"/.config/bspwm/src/rofi-themes/PowerMenu.rasi
}

chosen=$(printf "%s\n" "${options[@]}" | rofi_cmd)

case $chosen in
" Apagar")
  systemctl poweroff
  ;;
" Reiniciar")
  systemctl reboot
  ;;
" Bloquear")
  ScreenLocker
  ;;
" Suspender")
  mpc -q pause
  amixer set Master mute
  systemctl suspend
  ;;
" Salir")
  bspc quit
  ;;
esac
