[font]
size = 10

builtin_box_drawing = true

normal = { family = "JetBrainsMono Nerd Font"
bold = { family = "JetBrainsMono Nerd Font"
italic = { family = "JetBrainsMono Nerd Font"
bold_italic = { family = "JetBrainsMono Nerd Font"
