# Default colors
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

# Cursor colors
[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

# Normal colors
[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#8fcc4c"
yellow = "#e0af68"
blue = "#61A3B1"
magenta = "#bb9af7"
cyan = "#93E5E5"
white = "#F9FCFE"

# Bright colors
[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#81cf2e"
yellow = "#e0af68"
blue = "#6FBACA"
magenta = "#bb9af7"
cyan = "#a4ffff"
white = "#f7f8f9"
