#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
## Manager Workspaces
workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

## 2 > web (always open web browser on workspace-2)
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on
bspc rule -a Google-chrome desktop='^2' follow=on focus=on
bspc rule -a Vivaldi desktop='^2' follow=on focus=on
bspc rule -a megasync desktop='^3' follow=on focus=on state=floating

## 3 > files (always open file manager on workspace-3)
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
	bspc rule -a $i desktop='^3' follow=on focus=on
done

## 4 > code (always open editors on workspace-4)
declare -a code=(Geany xed code-oss)
for i in ${code[@]}; do
	bspc rule -a $i desktop='^4' follow=on focus=on
done

## 5 > office and docs (always open office/doc apps on workspace-5)
declare -a office=(Gucharmap Atril Evince
	libreoffice-writer libreoffice-calc libreoffice-impress
	libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
	bspc rule -a $i desktop='^5' follow=on focus=on
done

## 6 > communication (always open communication apps on workspace-6)
declare -a comm=(thunderbird Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
	bspc rule -a $i desktop='^6' follow=on focus=on
done

## 7 > media (always open media apps on workspace-7)
declare -a media=(spotify vlc parole Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs)
for i in ${media[@]}; do
	bspc rule -a $i desktop='^7' state=floating follow=on focus=on
done

## 8 > system (always open system apps on workspace-8)
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr
	System-config-printer.py Pavucontrol Exo-helper-1
	Xfce4-power-manager-settings)
for i in ${settings[@]}; do
	bspc rule -a $i desktop='^8' state=floating follow=on focus=on
done

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places'
	Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
	bspc rule -a $i state=floating follow=on focus=on
done

bspc rule -a Conky state=floating manage=off
bspc rule -a plank state=floating follow=on
bspc rule -a stalonetray state=floating manage=off

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"


# Kill if already running
killall -9 dunst udiskie 
#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
# nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Super_L|d' &
ksuperkey -e 'Super_R=Super_R|d' &

# start conky
exec conky -p 2 &

# Start mpd
exec mpd &

# Start volume icon
# exec volumeicon &

# Start udiskie
exec udiskie -t &

# Random Wallpaper
exec ~/.config/bspwm/scripts/randomwallpapers.sh ~/Imágenes/wallpapers/ 300 & 
